name: Publish to NPM

on:
  release:
    types: [published]

jobs:
  npm-publish:
    name: npm-publish
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: 12
        registry-url: https://registry.npmjs.org/

    - run: yarn install
    - run: npm test

    - name: Publish package to NPM 📦
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
